-- 修复数据库表权限
-- 授予所有表的权限给 postgres 用户

-- 授予所有表的SELECT, INSERT, UPDATE, DELETE权限
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres;

-- 授予序列权限（用于自增ID）
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO postgres;

-- 授予未来创建表的默认权限
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres;
